Repository fcpkata/inventory, pull requests merged in 2020-07, with the labels that each got.

#2 Updated probePath for checking application health
  charts/inventory/values.yaml
Labels: approved, size/XS

#8 Added Actuator dependency
  build.gradle
  charts/inventory/values.yaml
Labels: approved, lgtm, size/XS

#7 Reactored existing code and added logic to save into product details …
  charts/inventory/values.yaml
  charts/preview/requirements.yaml
  src/main/java/com/inventory/controller/InventoryController.java
  src/main/java/com/inventory/exception/ValidationError.java
  src/main/java/com/inventory/model/Category.java
  src/main/java/com/inventory/model/Item.java
  src/main/java/com/inventory/model/Product.java
  src/main/java/com/inventory/model/ProductInformation.java
  src/main/java/com/inventory/model/ProductInformations.java
  src/main/java/com/inventory/model/ProductMetadata.java
  src/main/java/com/inventory/model/ProductRequest.java
  src/main/java/com/inventory/repository/ItemRepository.java
  src/main/java/com/inventory/service/AddItemService.java
  src/main/java/com/inventory/service/CatalogService.java
  src/main/java/com/inventory/service/SellerIdValidationService.java
  src/test/java/com/inventory/acceptance/InventoryIntegrationTest.java
  src/test/java/com/inventory/controller/InventoryControllerTest.java
  src/test/java/com/inventory/service/AddItemServiceTest.java
  src/test/java/com/inventory/service/CatalogServiceTest.java
  src/test/java/com/inventory/service/SellerIdValidationServiceTest.java
  src/test/resources/addProduct_InvalidSellerId.json
Labels: approved, lgtm, size/XL
